/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.CKasir;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author MSI-PC
 */
public class VKasir extends javax.swing.JFrame {

    /**
     * Creates new form VKasir
     */
    CKasir controller;
    private int totalQuantity;
    private List<Integer> idProduks;
    private List<Integer> idWarnas;
    private List<String> imeis;
    private String lvl_akses;
    private int user_id;

    public VKasir(String lvl_akses, int user_id) {
        initComponents();
        controller = new CKasir(this);
        controller.isiDataProduk();
        controller.isiDataWarna();
        controller.isiDataJPembayaran();
        this.lvl_akses = lvl_akses;
        this.user_id = user_id;
    }

    public JComboBox<String> getCboNamaProduk() {
        return cboNamaProduk;
    }

    public JComboBox<String> getCboWarnaProduk() {
        return cboWarnaProduk;
    }

    public JTable getTblTransaksi() {
        return tblTransaksi;
    }

    public JTextField getTxtImei() {
        return txtImei;
    }

    public JTextField getTxtNamaCustomer() {
        return txtNamaCustomer;
    }

    public JTextField getTxtNik() {
        return txtNik;
    }

    public JTextField getTxtNoHp() {
        return txtNoHp;
    }

    public JComboBox<String> getCboJPembayaran() {
        return cboJPembayaran;
    }

    public int getTotalQuantity() {
        return totalQuantity;
    }

    public void setTotalQuantity(int totalQuantity) {
        this.totalQuantity = totalQuantity;
    }

    public List<Integer> getIdProduks() {
        return idProduks;
    }

    public void setIdProduks(List<Integer> idProduks) {
        this.idProduks = idProduks;
    }

    public List<Integer> getIdWarnas() {
        return idWarnas;
    }

    public void setIdWarnas(List<Integer> idWarnas) {
        this.idWarnas = idWarnas;
    }

    public List<String> getImeis() {
        return imeis;
    }

    public void setImeis(List<String> imeis) {
        this.imeis = imeis;
    }

    public JTextField getTxtBayar() {
        return txtBayar;
    }

    public JTextArea getTxaStruk() {
        return txaStruk;
    }

    public int getUser_id() {
        return user_id;
    }
    
    private VKasir() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNamaCustomer = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNik = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNoHp = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cboNamaProduk = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cboWarnaProduk = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        slpTransaksi = new javax.swing.JScrollPane();
        tblTransaksi = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaStruk = new javax.swing.JTextArea();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnConfirm = new javax.swing.JButton();
        btnCetak = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        cboJPembayaran = new javax.swing.JComboBox<>();
        txtImei = new javax.swing.JTextField();
        txtBayar = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Data Customer :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 10, 120, 40);

        jLabel2.setText("Nama Customer");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 60, 100, 30);
        getContentPane().add(txtNamaCustomer);
        txtNamaCustomer.setBounds(150, 60, 230, 30);

        jLabel3.setText("NIK");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 110, 40, 30);
        getContentPane().add(txtNik);
        txtNik.setBounds(150, 110, 230, 30);

        jLabel4.setText("No. HP");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 160, 80, 30);
        getContentPane().add(txtNoHp);
        txtNoHp.setBounds(150, 160, 230, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Data Pembelian :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(450, 20, 130, 20);

        jLabel6.setText("Nama Produk");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(450, 60, 90, 30);

        cboNamaProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboNamaProdukActionPerformed(evt);
            }
        });
        getContentPane().add(cboNamaProduk);
        cboNamaProduk.setBounds(550, 60, 180, 30);

        jLabel7.setText("Warna Produk");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(450, 110, 90, 30);

        cboWarnaProduk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboWarnaProdukMouseClicked(evt);
            }
        });
        cboWarnaProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboWarnaProdukActionPerformed(evt);
            }
        });
        getContentPane().add(cboWarnaProduk);
        cboWarnaProduk.setBounds(550, 110, 180, 30);

        jLabel8.setText("IMEI");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(450, 160, 50, 30);

        tblTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Nama Produk", "Warna Produk", "IMEI"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        slpTransaksi.setViewportView(tblTransaksi);
        if (tblTransaksi.getColumnModel().getColumnCount() > 0) {
            tblTransaksi.getColumnModel().getColumn(0).setResizable(false);
            tblTransaksi.getColumnModel().getColumn(1).setResizable(false);
            tblTransaksi.getColumnModel().getColumn(2).setResizable(false);
            tblTransaksi.getColumnModel().getColumn(3).setResizable(false);
        }

        getContentPane().add(slpTransaksi);
        slpTransaksi.setBounds(30, 270, 810, 350);

        txaStruk.setEditable(false);
        txaStruk.setColumns(20);
        txaStruk.setRows(5);
        jScrollPane2.setViewportView(txaStruk);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(890, 10, 380, 270);

        btnAdd.setBackground(new java.awt.Color(204, 153, 0));
        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd);
        btnAdd.setBounds(750, 60, 90, 30);

        btnDelete.setBackground(new java.awt.Color(204, 153, 0));
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete);
        btnDelete.setBounds(750, 110, 90, 30);

        btnConfirm.setBackground(new java.awt.Color(204, 153, 0));
        btnConfirm.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnConfirm.setText("CONFIRM");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });
        getContentPane().add(btnConfirm);
        btnConfirm.setBounds(30, 640, 90, 30);

        btnCetak.setBackground(new java.awt.Color(204, 153, 0));
        btnCetak.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCetak.setText("CETAK");
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });
        getContentPane().add(btnCetak);
        btnCetak.setBounds(130, 640, 90, 30);

        jLabel9.setText("Jenis Pembayaran");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(40, 210, 110, 30);

        getContentPane().add(cboJPembayaran);
        cboJPembayaran.setBounds(150, 210, 230, 30);
        getContentPane().add(txtImei);
        txtImei.setBounds(550, 160, 180, 30);

        txtBayar.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        txtBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBayarActionPerformed(evt);
            }
        });
        getContentPane().add(txtBayar);
        txtBayar.setBounds(651, 630, 190, 40);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel10.setText("Rp");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(600, 620, 50, 50);

        setSize(new java.awt.Dimension(1294, 727));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try {
            // TODO add your handling code here:
            controller.insertDetail();
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, ex.getException());
        }
        controller.viewDetail();
    }//GEN-LAST:event_btnAddActionPerformed

    private void cboNamaProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboNamaProdukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboNamaProdukActionPerformed

    private void cboWarnaProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboWarnaProdukActionPerformed
    }//GEN-LAST:event_cboWarnaProdukActionPerformed

    private void cboWarnaProdukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboWarnaProdukMouseClicked
    }//GEN-LAST:event_cboWarnaProdukMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        controller.deleteDetail();
        controller.viewDetail();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        try {
            // TODO add your handling code here:
            controller.Konfirmasi();
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, ex.getException());
        }
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void txtBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBayarActionPerformed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        try {
            // TODO add your handling code here:
            controller.cetak();
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, ex.getException());
        }
    }//GEN-LAST:event_btnCetakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VKasir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnDelete;
    private javax.swing.JComboBox<String> cboJPembayaran;
    private javax.swing.JComboBox<String> cboNamaProduk;
    private javax.swing.JComboBox<String> cboWarnaProduk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane slpTransaksi;
    private javax.swing.JTable tblTransaksi;
    private javax.swing.JTextArea txaStruk;
    private javax.swing.JTextField txtBayar;
    private javax.swing.JTextField txtImei;
    private javax.swing.JTextField txtNamaCustomer;
    private javax.swing.JTextField txtNik;
    private javax.swing.JTextField txtNoHp;
    // End of variables declaration//GEN-END:variables
}
