/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.CProduk;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author hp
 */
public class VProduk extends javax.swing.JFrame {

    /**
     * Creates new form VProduk
     */
    CProduk controller;
    private List<Integer> ids;
    private String lvl_akses;
    private int user_id;

    public VProduk(String lvl_akses, int user_id) {
        initComponents();
        controller = new CProduk(this);
        controller.view();
        this.lvl_akses = lvl_akses;
        this.user_id = user_id;
    }

    public JTable getTblProduk() {
        return tblProduk;
    }

    public JTextField getTxtHarga() {
        return txtHarga;
    }

    public JTextField getTxtModal() {
        return txtModal;
    }

    public JTextField getTxtNamaProduk() {
        return txtNama;
    }

    public JTextField getTxtSubsidi() {
        return txtSubsidi;
    }

    public List<Integer> getIds() {
        return ids;
    }

    public void setIds(List<Integer> ids) {
        this.ids = ids;
    }

    private VProduk() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtHarga = new javax.swing.JTextField();
        txtModal = new javax.swing.JTextField();
        txtSubsidi = new javax.swing.JTextField();
        btnInsert = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        slpProduk = new javax.swing.JScrollPane();
        tblProduk = new javax.swing.JTable();
        btnClear = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(null);

        jLabel2.setText("Nama Produk :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 60, 80, 30);

        jLabel4.setText("Harga Produk :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 110, 80, 30);

        jLabel1.setText("Modal Produk :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 160, 90, 30);

        jLabel3.setText("Subsidi Produk :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 210, 90, 30);
        getContentPane().add(txtNama);
        txtNama.setBounds(120, 60, 300, 30);
        getContentPane().add(txtHarga);
        txtHarga.setBounds(120, 110, 300, 30);
        getContentPane().add(txtModal);
        txtModal.setBounds(120, 160, 300, 30);
        getContentPane().add(txtSubsidi);
        txtSubsidi.setBounds(120, 210, 300, 30);

        btnInsert.setBackground(new java.awt.Color(204, 153, 0));
        btnInsert.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnInsert.setText("INSERT");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsert);
        btnInsert.setBounds(120, 260, 80, 30);

        btnUpdate.setBackground(new java.awt.Color(204, 153, 0));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate);
        btnUpdate.setBounds(230, 260, 80, 30);

        btnDelete.setBackground(new java.awt.Color(204, 153, 0));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete);
        btnDelete.setBounds(340, 260, 80, 30);

        tblProduk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No", "Nama Produk", "Harga Produk", "Modal Produk", "Subsidi Produk", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProduk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProdukMouseClicked(evt);
            }
        });
        slpProduk.setViewportView(tblProduk);
        if (tblProduk.getColumnModel().getColumnCount() > 0) {
            tblProduk.getColumnModel().getColumn(0).setResizable(false);
            tblProduk.getColumnModel().getColumn(1).setResizable(false);
            tblProduk.getColumnModel().getColumn(2).setResizable(false);
            tblProduk.getColumnModel().getColumn(3).setResizable(false);
            tblProduk.getColumnModel().getColumn(4).setResizable(false);
            tblProduk.getColumnModel().getColumn(5).setResizable(false);
        }

        getContentPane().add(slpProduk);
        slpProduk.setBounds(480, 50, 720, 550);

        btnClear.setBackground(new java.awt.Color(204, 153, 0));
        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear);
        btnClear.setBounds(480, 620, 80, 40);

        btnBack.setBackground(new java.awt.Color(204, 204, 204));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack);
        btnBack.setBounds(1200, 10, 70, 20);

        setSize(new java.awt.Dimension(1294, 727));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        // TODO add your handling code here:
        try {
            controller.insert();
            if (!txtNama.getText().isBlank()
                    && !txtHarga.getText().isBlank()
                    && !txtModal.getText().isBlank()
                    && !txtSubsidi.getText().isBlank()) {
                controller.clear();
            }
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        controller.view();
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        try {
            controller.update();
            if (!txtNama.getText().isBlank()
                    && !txtHarga.getText().isBlank()
                    && !txtModal.getText().isBlank()
                    && !txtSubsidi.getText().isBlank()) {
                controller.clear();
            }
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        controller.view();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int option = JOptionPane.showConfirmDialog(null, "Yakin Ingin Menghapus Data?", "Alert", JOptionPane.YES_NO_OPTION);
        try {
            if (option == JOptionPane.YES_OPTION) {
                controller.delete();
            }
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        controller.view();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        controller.clear();
    }//GEN-LAST:event_btnClearActionPerformed

    private void tblProdukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProdukMouseClicked
        // TODO add your handling code here:
        controller.search();
    }//GEN-LAST:event_tblProdukMouseClicked

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        dispose();
        new VSupplier(lvl_akses, user_id).setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VProduk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane slpProduk;
    private javax.swing.JTable tblProduk;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtModal;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtSubsidi;
    // End of variables declaration//GEN-END:variables
}
